/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5649acb256b67ab99c9c1cc1f38fa354)
interface __BaseEnv_Env {
	LATENCY: AnalyticsEngineDataset;
	AUTH_RATE_LIMITER: RateLimit;
	GAME_RATE_LIMITER: RateLimit;
	ME_RATE_LIMITER: RateLimit;
	ADMIN_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	DATABASE_URL: string;
	BETTER_AUTH_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	ADMIN_EMAIL: string;
	BETTER_AUTH_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "BETTER_AUTH_SECRET" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "ADMIN_EMAIL" | "BETTER_AUTH_URL">> {}
}
