/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c59f0c71a90339321f69eae7126d2c5e)
interface __BaseEnv_Env {
	AUTH_RATE_LIMITER: RateLimit;
	GAME_RATE_LIMITER: RateLimit;
	ME_RATE_LIMITER: RateLimit;
	ADMIN_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.svelte-kit/cloudflare/_worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
