// Avatar-list pipeline (Phase-2 D4): canonical SERVER list → generated
// CLIENT artifact, mirroring the word-list pipeline (`scripts/build-word-list.ts`).
//   canonical source: src/server/data/avatar-emojis.ts   (committed, server-owned;
//                      regenerated by `bun run avatar-data` — DO NOT hand-edit)
//   client artifact:  src/lib/shared/config/avatar-emojis.generated.ts (generated, committed)
// Rules enforced at build time (fails the build on violations):
//   - stable order (the committed array order IS the artifact order)
//   - non-empty emoji + label per entry
//   - group per entry, from the pinned Unicode group set (Phase-6 category metadata)
//   - no duplicate emoji, no duplicate label
// The parity unit test (tests/unit/avatar-list.test.ts) pins canonical ↔
// generated equality; CI runs `bun run avatar-list` + `git diff --exit-code`.
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { AVATAR_EMOJIS, AVATAR_GROUPS, type AvatarEmoji } from '../src/server/data/avatar-emojis';

const OUT = resolve('src/lib/shared/config/avatar-emojis.generated.ts');

/** Throws on any violation; returns the validated list (deterministic). */
export function validateAvatarList(emojis: readonly AvatarEmoji[]): readonly AvatarEmoji[] {
	const groups = new Set<string>(AVATAR_GROUPS);
	const seenEmoji = new Set<string>();
	const seenLabels = new Set<string>();
	for (const entry of emojis) {
		if (typeof entry.emoji !== 'string' || entry.emoji.length === 0) {
			throw new Error(`avatar entry missing emoji: ${JSON.stringify(entry)}`);
		}
		if (typeof entry.label !== 'string' || entry.label.length === 0) {
			throw new Error(`avatar entry missing label: ${JSON.stringify(entry)}`);
		}
		if (typeof entry.group !== 'string' || entry.group.length === 0) {
			throw new Error(`avatar entry missing group: ${JSON.stringify(entry)}`);
		}
		if (!groups.has(entry.group)) {
			throw new Error(`avatar entry has unknown group "${entry.group}": ${JSON.stringify(entry)}`);
		}
		if (seenEmoji.has(entry.emoji)) throw new Error(`duplicate avatar emoji: ${entry.emoji}`);
		if (seenLabels.has(entry.label)) throw new Error(`duplicate avatar label: ${entry.label}`);
		seenEmoji.add(entry.emoji);
		seenLabels.add(entry.label);
	}
	return emojis;
}

/** The generated client module — the picker's allow-list (D4) + category metadata. */
export function renderAvatarArtifact(emojis: readonly AvatarEmoji[]): string {
	const groups = AVATAR_GROUPS.map((g) => `\t'${g.replace(/'/g, "\\'")}'`).join(',\n');
	return `// GENERATED by \`bun run avatar-list\` — DO NOT HAND-EDIT.
// Client twin of the canonical SERVER avatar allow-list
// (src/server/data/avatar-emojis.ts — the authoritative source).
// Chosen set (pre-phase-6 production policy, documented in
// docs/phases/pre-phase-6/production-data-finalization.md): every fully-qualified
// Unicode Emoji 17.0 RGI sequence (3,944 entries), codepoint-sorted; labels are
// the CLDR short names; each entry carries its Unicode group (Phase-6 category
// metadata for the picker). Count + ordering are pinned by
// tests/unit/avatar-list.test.ts and the CI \`git diff --exit-code\` step.
export type AvatarEmoji = {
	emoji: string;
	label: string;
	/** Unicode group (UTS #51 \`# group:\` line) — client category metadata. */
	group: string;
};

/** The 9 Unicode emoji groups, in the authoritative file order (deterministic). */
export const AVATAR_GROUPS: readonly string[] = [
${groups}
] as const;

export const AVATAR_EMOJIS: readonly AvatarEmoji[] = ${JSON.stringify(emojis, null, '\t')} as const;
`;
}

/** CLI entry (`bun run avatar-list`). */
if (import.meta.main) {
	const validated = validateAvatarList(AVATAR_EMOJIS);
	writeFileSync(OUT, renderAvatarArtifact(validated));
	console.log(`built ${validated.length} avatars → ${OUT}`);
}
