// NC3/NG7 — valid-guesses pipeline: canonical source → public client artifact
// AND the server's authoritative validation dictionary (NG7 "one canonical
// source → server + client artifacts with an automated equality/version
// build check").
//   source:        src/server/data/valid-guesses.source.txt  (committed, public)
//   server artifact: src/server/data/valid-guesses.generated.ts (generated, committed)
//   client artifact: src/lib/shared/data/valid-guesses.json   (generated, committed)
// Rules enforced at build time (fails the build on violations):
//   - one word per line (blank lines and `#` comments ignored)
//   - lowercase a-z only, exactly 5 letters
//   - no duplicates, output sorted
// The answer pool is a SEPARATE private pipeline (scripts/seed/, gitignored)
// and must never enter these artifacts (NC3/NG16 provenance recorded there).
//
// The core logic is exported so the rules are unit-testable
// (tests/unit/build-word-list.test.ts); running this file directly
// (`bun run word-list`) rebuilds both artifacts from the canonical source.
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const SOURCE = resolve('src/server/data/valid-guesses.source.txt');
const OUT = resolve('src/lib/shared/data/valid-guesses.json');
const SERVER_OUT = resolve('src/server/data/valid-guesses.generated.ts');

/** The generated server module — the authoritative validation dictionary. */
export function renderServerArtifact(words: string[]): string {
	return `// GENERATED by \`bun run word-list\` — DO NOT HAND-EDIT.
// Authoritative SERVER dictionary for guess validation (Architecture §1487–1501).
// Source: src/server/data/valid-guesses.source.txt (canonical, committed).
// Client twin: src/lib/shared/data/valid-guesses.json — byte-equal content,
// checked by tests/unit/word-list-server.test.ts.
// This list is PUBLIC (safe for the client bundle). The answer pool is a
// separate private pipeline and never appears here.
export const VALID_GUESSES: readonly string[] = ${JSON.stringify(words, null, '\t')} as const;

export const VALID_GUESS_SET: ReadonlySet<string> = new Set(VALID_GUESSES);
`;
}

/**
 * Parse + validate the source text. Throws on any violation (invalid word
 * shape or duplicate), returns the sorted unique word list otherwise.
 * Deterministic: same source → same output, always.
 */
export function parseWordList(sourceText: string): string[] {
	const lines = sourceText
		.split('\n')
		.map((l) => l.trim())
		.filter((l) => l.length > 0 && !l.startsWith('#'));

	const violations: string[] = [];
	const seen = new Set<string>();
	for (const line of lines) {
		if (!/^[a-z]{5}$/.test(line)) {
			violations.push(`not a lowercase 5-letter word: "${line}"`);
			continue;
		}
		if (seen.has(line)) violations.push(`duplicate word: "${line}"`);
		seen.add(line);
	}
	if (violations.length > 0) {
		throw new Error(`valid-guesses source invalid (${violations.length}): ${violations.join('; ')}`);
	}
	return [...seen].sort();
}

/** Build the public artifact from the canonical committed source. */
export function buildWordList(sourcePath: string, outPath: string): string[] {
	const sorted = parseWordList(readFileSync(sourcePath, 'utf8'));
	writeFileSync(outPath, JSON.stringify(sorted, null, 1) + '\n');
	return sorted;
}

/**
 * Build BOTH artifacts (client JSON + server TS dictionary) from the
 * canonical committed source. Deterministic: same source → same outputs.
 */
export function buildWordArtifacts(sourcePath: string, jsonOutPath: string, tsOutPath: string): string[] {
	const sorted = buildWordList(sourcePath, jsonOutPath);
	writeFileSync(tsOutPath, renderServerArtifact(sorted));
	return sorted;
}

// CLI entry (`bun run word-list`); import.meta.main is true only when this
// file is executed directly, so tests can import the functions harmlessly.
if (import.meta.main) {
	const words = buildWordArtifacts(SOURCE, OUT, SERVER_OUT);
	console.log(`built ${words.length} words → ${OUT} + ${SERVER_OUT}`);
}