// Avatar-list pipeline (Phase-2 D4): canonical SERVER list → generated
// CLIENT artifact, mirroring the word-list pipeline (`scripts/build-word-list.ts`).
//   canonical source: src/server/data/avatar-emojis.ts   (committed, server-owned)
//   client artifact:  src/lib/shared/config/avatar-emojis.generated.ts (generated, committed)
// Rules enforced at build time (fails the build on violations):
//   - stable order (the committed array order IS the artifact order)
//   - non-empty emoji + label per entry
//   - no duplicate emoji, no duplicate label
// The parity unit test (tests/unit/avatar-list.test.ts) pins canonical ↔
// generated equality; CI runs `bun run avatar-list` + `git diff --exit-code`.
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { AVATAR_EMOJIS, type AvatarEmoji } from '../src/server/data/avatar-emojis';

const OUT = resolve('src/lib/shared/config/avatar-emojis.generated.ts');

/** Throws on any violation; returns the validated list (deterministic). */
export function validateAvatarList(emojis: readonly AvatarEmoji[]): readonly AvatarEmoji[] {
	const seenEmoji = new Set<string>();
	const seenLabels = new Set<string>();
	for (const entry of emojis) {
		if (typeof entry.emoji !== 'string' || entry.emoji.length === 0) {
			throw new Error(`avatar entry missing emoji: ${JSON.stringify(entry)}`);
		}
		if (typeof entry.label !== 'string' || entry.label.length === 0) {
			throw new Error(`avatar entry missing label: ${JSON.stringify(entry)}`);
		}
		if (seenEmoji.has(entry.emoji)) throw new Error(`duplicate avatar emoji: ${entry.emoji}`);
		if (seenLabels.has(entry.label)) throw new Error(`duplicate avatar label: ${entry.label}`);
		seenEmoji.add(entry.emoji);
		seenLabels.add(entry.label);
	}
	return emojis;
}

/** The generated client module — the picker's allow-list (D4). */
export function renderAvatarArtifact(emojis: readonly AvatarEmoji[]): string {
	return `// GENERATED by \`bun run avatar-list\` — DO NOT HAND-EDIT.
// Client twin of the canonical SERVER avatar allow-list
// (src/server/data/avatar-emojis.ts — the authoritative source).
// Chosen set (D4, documented in docs/contradictions-and-gaps.md): 24 curated
// entries, stable order, no skin-tone sequences. Count + ordering are pinned
// by tests/unit/avatar-list.test.ts and the CI \`git diff --exit-code\` step.
export type AvatarEmoji = {
	emoji: string;
	label: string;
};

export const AVATAR_EMOJIS: readonly AvatarEmoji[] = ${JSON.stringify(emojis, null, '\t')} as const;
`;
}

/** CLI entry point (`bun run avatar-list`). */
if (import.meta.main) {
	const validated = validateAvatarList(AVATAR_EMOJIS);
	writeFileSync(OUT, renderAvatarArtifact(validated));
	console.log(`built ${validated.length} avatars → ${OUT}`);
}