// GENERATED by `bun run word-list` — DO NOT HAND-EDIT.
// Authoritative SERVER dictionary for guess validation (Architecture §1487–1501).
// Source: src/server/data/valid-guesses.source.txt (canonical, committed).
// Client twin: src/lib/shared/data/valid-guesses.json — byte-equal content,
// checked by tests/unit/word-list-server.test.ts.
// This list is PUBLIC (safe for the client bundle). The answer pool is a
// separate private pipeline and never appears here.
export const VALID_GUESSES: readonly string[] = [
	"about",
	"after",
	"again",
	"below",
	"candy",
	"drain",
	"early",
	"flame",
	"grain",
	"hello",
	"juice",
	"light",
	"mount",
	"north",
	"ocean",
	"plant",
	"quick",
	"river",
	"stone",
	"tiger"
] as const;

export const VALID_GUESS_SET: ReadonlySet<string> = new Set(VALID_GUESSES);
