// GENERATED by `bun run avatar-list` — DO NOT HAND-EDIT.
// Client twin of the canonical SERVER avatar allow-list
// (src/server/data/avatar-emojis.ts — the authoritative source).
// Chosen set (D4, documented in docs/contradictions-and-gaps.md): 24 curated
// entries, stable order, no skin-tone sequences. Count + ordering are pinned
// by tests/unit/avatar-list.test.ts and the CI `git diff --exit-code` step.
export type AvatarEmoji = {
	emoji: string;
	label: string;
};

export const AVATAR_EMOJIS: readonly AvatarEmoji[] = [
	{
		"emoji": "🦊",
		"label": "Fox"
	},
	{
		"emoji": "🐺",
		"label": "Wolf"
	},
	{
		"emoji": "🐼",
		"label": "Panda"
	},
	{
		"emoji": "🐸",
		"label": "Frog"
	},
	{
		"emoji": "🦉",
		"label": "Owl"
	},
	{
		"emoji": "🐨",
		"label": "Koala"
	},
	{
		"emoji": "🦁",
		"label": "Lion"
	},
	{
		"emoji": "🐯",
		"label": "Tiger"
	},
	{
		"emoji": "🐷",
		"label": "Pig"
	},
	{
		"emoji": "🐵",
		"label": "Monkey"
	},
	{
		"emoji": "🐙",
		"label": "Octopus"
	},
	{
		"emoji": "🦄",
		"label": "Unicorn"
	},
	{
		"emoji": "🐲",
		"label": "Dragon"
	},
	{
		"emoji": "🦖",
		"label": "T-Rex"
	},
	{
		"emoji": "🐢",
		"label": "Turtle"
	},
	{
		"emoji": "🦈",
		"label": "Shark"
	},
	{
		"emoji": "🐬",
		"label": "Dolphin"
	},
	{
		"emoji": "🐝",
		"label": "Bee"
	},
	{
		"emoji": "🦋",
		"label": "Butterfly"
	},
	{
		"emoji": "🐞",
		"label": "Ladybug"
	},
	{
		"emoji": "🦀",
		"label": "Crab"
	},
	{
		"emoji": "🐧",
		"label": "Penguin"
	},
	{
		"emoji": "🦭",
		"label": "Seal"
	},
	{
		"emoji": "🐹",
		"label": "Hamster"
	}
] as const;
